import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai_Looped } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/theme";
import VisitorNavbar from "@/component/VisitorNavbar";
import SmeNavbar from "@/component/SmeNavbar";
import { NotificationProvider } from "@/context/NotificationContext";
import NavbarWrapper from "../component/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
});

const notoSansThaiLooped = Noto_Sans_Thai_Looped({
  variable: "--font-noto-sans-thai-looped",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["thai", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSansThaiLooped.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <NotificationProvider>
              <CssBaseline />
              <NavbarWrapper>{children}</NavbarWrapper>
            </NotificationProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
